### ISSUE TITLE
Create .env file

### ISSUE THREAD

**Issue by PascalLike** [emotional-cities/openapi-sdi#6]
Create an .env file and add it to .gitignore to store environmental variables (useful to initialize passwords to not default values etc)

**Comment by doublebyte1** [comment]
Addressed in this commit: https://github.com/emotional-cities/openapi-sdi/commit/5dea2d3b03604a709f38569c90e3650a8c06e46d

Should it be in master, instead of merge?

**Comment by doublebyte1** [comment]
I have added it to master
